services:
    ulysseus-toolbox-frontend:
        container_name: ulysseus-toolbox-frontend
        build:
            no_cache: true
            context: frontend
            args:
                NEXT_PUBLIC_BACKEND_AUTH_URL: ${NEXT_PUBLIC_BACKEND_AUTH_URL}
                NEXT_PUBLIC_BACKEND_SHAREPOINT_URL: ${NEXT_PUBLIC_BACKEND_SHAREPOINT_URL}
        restart: unless-stopped
        networks:
            - ulysseus_toolbox
        depends_on:
            ulysseus-toolbox-backend-sharepoint:
                condition: service_started
            ulysseus-toolbox-backend-auth:
                condition: service_started
    ulysseus-toolbox-backend-auth:
        container_name: ulysseus-toolbox-backend-auth
        build:
            no_cache: true
            context: backend-auth
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - ulysseus_toolbox
    ulysseus-toolbox-backend-sharepoint:
        container_name: ulysseus-toolbox-backend-sharepoint
        build:
            no_cache: true
            context: backend-sharepoint
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - ulysseus_toolbox
            - azure_internal
    ulysseus-toolbox-nginx:
        container_name: ulysseus-toolbox-nginx
        image: nginx:1.28.0
        volumes:
            - ./nginx:/etc/nginx/conf.d/
        restart: unless-stopped
        ports:
            - "3085:80"
        networks:
            - ulysseus_toolbox
        depends_on:
            ulysseus-toolbox-frontend:
                condition: service_started
                restart: true
networks:
    ulysseus_toolbox:
        name: ulysseus_toolbox
        driver: bridge
        enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 172.31.9.0/24
    azure_internal:
        external: true
        name: azure_internal
