services:
    ulysseus-toolbox-frontend:
        extends:
            file: docker-services.yml
            service: frontend
    ulysseus-toolbox-backend-auth:
        extends:
            file: docker-services.yml
            service: backend-auth
    ulysseus-toolbox-backend-sharepoint:
        extends:
            file: docker-services.yml
            service: backend-sharepoint
        networks:
            - azure_internal
    ulysseus-toolbox-nginx:
        extends:
            file: docker-services.yml
            service: nginx

networks:
    ulysseus_toolbox:
        name: ulysseus_toolbox
        driver: bridge
        enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 172.31.9.0/24
    azure_internal:
        external: true
        name: azure_internal
